# Generated by Django 5.2.4 on 2025-07-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pic', models.ImageField(upload_to='about/%Y/%m')),
                ('second_pic', models.ImageField(upload_to='about/%Y/%m')),
                ('third_pic', models.ImageField(upload_to='about/%Y/%m')),
                ('fourth_pic', models.ImageField(upload_to='about/%Y/%m')),
                ('description', models.TextField()),
                ('experience', models.PositiveIntegerField()),
                ('masterchefs', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'aboutt',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256)),
                ('profession', models.CharField(max_length=256)),
                ('client_pic', models.ImageField(upload_to='client_pics/%Y/%m')),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('start_and_end_days', models.CharField(max_length=256)),
                ('time_1', models.CharField(max_length=256)),
                ('time_sunday', models.CharField(max_length=256)),
                ('newsletter_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'footer',
                'verbose_name_plural': 'footers',
                'db_table': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Home_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_theme', models.CharField(max_length=256)),
                ('service_description', models.TextField()),
            ],
            options={
                'verbose_name': 'home_service',
                'verbose_name_plural': 'home_services',
                'db_table': 'home_service',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'main',
                'verbose_name_plural': 'mainn',
                'db_table': 'main',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'people number',
                'verbose_name_plural': 'people numbers',
                'db_table': 'people number',
            },
        ),
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('designation', models.CharField(max_length=256)),
                ('pic', models.ImageField(upload_to='ourteam/%Y/%m')),
            ],
            options={
                'verbose_name': 'ourteam',
                'verbose_name_plural': 'ourteams',
                'db_table': 'ourteam',
            },
        ),
        migrations.CreateModel(
            name='Book_Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('special_request', models.TextField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.order')),
            ],
        ),
    ]
