# Generated by Django 5.2.4 on 2025-07-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_email', models.EmailField(max_length=254)),
                ('general_email', models.EmailField(max_length=254)),
                ('technical_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'contact_email',
                'verbose_name_plural': 'contact_emails',
                'db_table': 'contact_email',
            },
        ),
    ]
