# Generated by Django 5.2.4 on 2025-07-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
    ]
