# Generated by Django 5.2.4 on 2025-07-21 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0005_category_dishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
