# Generated by Django 5.2.4 on 2025-07-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0006_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_online',
            options={'verbose_name': 'book online', 'verbose_name_plural': 'booking online'},
        ),
        migrations.AlterModelTable(
            name='book_online',
            table='book online',
        ),
    ]
