# Generated by Django 5.2.4 on 2025-07-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0008_home_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_online',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
