# Generated by Django 5.2.4 on 2025-07-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0009_alter_book_online_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
