# Generated by Django 5.2.4 on 2025-07-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0010_ourteam_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'about', 'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='contact_email',
            options={'verbose_name': 'contact email', 'verbose_name_plural': 'contact emails'},
        ),
        migrations.AlterModelOptions(
            name='home_service',
            options={'verbose_name': 'home service', 'verbose_name_plural': 'home services'},
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'main', 'verbose_name_plural': 'main'},
        ),
    ]
