# Generated by Django 5.2.4 on 2025-07-28 06:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0011_alter_about_options_alter_contact_email_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='first_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='about/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='about',
            name='fourth_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='about/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='about',
            name='second_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='about/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='about',
            name='third_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='about/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='client_pics/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='dishes/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='main',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=95, scale=0.5, size=[200, 1000], upload_to='main/Y%/%m'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='ourteam/%Y/%m'),
        ),
    ]
