# Generated by Django 5.2.4 on 2025-07-28 06:48

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0012_alter_about_first_pic_alter_about_fourth_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], upload_to='main/Y%/%m'),
        ),
    ]
