# Generated by Django 5.2.4 on 2025-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0013_alter_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
